# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the  directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

